### ISSUE TITLE
Fix regex validation for email

### ISSUE THREAD

**Issue by GiuseppeTG** [learnwithalfred/portfolio-website#15]
Your regex expression is not working properly.

https://github.com/learnwithalfred/portfolio-website/blob/b00e136e829e971cff8f057ab083e3af756a4f76/js/contact-form.js#L19

Your regex: /[a-z]+`\.`[@][a-z]+\.[a-z]{2,3}/
It is checking for a dot before the "@" symbol. 

Try this regex: /[a-z]+[@][a-z]+\.[a-z]{2,3}/ 

 :raised_hands:

**Comment by thinktrans** [comment]
If I may, I would like to request you to keep it as simple as this:
`<e-mail local part>@<domain name>`
Which can be implemented as 

For `<e-mail local part>` - Follow the guidelines by the "Universal Acceptance Steering Group" - UASG-026 - https://uasg.tech/download/uasg-028-considerations-for-naming-internationalized-email-mailboxes-en/

For `<domain name>`, you can follow any domain validation methodology using standard libraries, depending on your programming language. For the recent studies on the subject, follow the document UASG-018A - https://uasg.tech/download/uasg-018a-ua-compliance-of-some-programming-language-libraries-and-frameworks-en/.
